### ISSUE TITLE
package name search in `ExtraVersionOption` is bugged

### ISSUE THREAD

**Issue by MePsyDuck** [kdeldycke/click-extra#729]
Commit [1877dc](https://github.com/kdeldycke/click-extra/commit/1877dc82b4f4e01f8fd0dd8e7a429d05d2acfb95#diff-dbab37b0dbc6ee3e519c216cc81f31714657d60bbac18c792fb3092bca4bcf1e) might be the culprit.

### Minimal example:
```python
from click_extra import extra_command


@extra_command()
def greet():
    print('hello world')


if __name__ == '__main__':
    greet()
```

When run using 
```
 python main.py --version
```

Produces
```
  File ".../lib/python3.10/site-packages/click_extra/version.py", line 300, in print_and_exit
    ctx.meta["click_extra.package_name"] = self.package_name
  File ".../lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File ".../lib/python3.10/site-packages/click_extra/version.py", line 188, in package_name
    raise RuntimeError(msg)
RuntimeError: Could not determine the package name automatically from the frame stack. Try passing 'package_name' instead.
```

Upon debugging I found `__package__` to be empty in `frame.f_globals`:
```
{'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x102921570>, '__spec__': None, '__file__': '<file_path>/main.py', '__builtins__': <module 'builtins' (built-in)>, 'extra_command': <function decorator_factory.<locals>.decorator at 0x1057ee950>, 'greet': <ExtraCommand greet>}
```

`frame_chain` was
```
[('click_extra.version', 'package_name'), ('functools', '__get__'), ('click_extra.version', 'print_and_exit'), ('click.core', 'process_value'), ('click.core', 'handle_parse_result'), ('click.core', 'parse_args'), ('cloup.constraints._support', 'parse_args'), ('click.core', 'make_context'), ('click_extra.commands', 'make_context'), ('click.core', 'main'), ('click_extra.commands', 'main'), ('click.core', '__call__'), ('__main__', '<module>')]
```

I was able to reproduce it in versions >=4.6.1.

**Comment by rasa** [comment]
The issue is `ExtraVersionOption` requires a `package_name` be passed to it, in top-level scripts.

https://github.com/kdeldycke/click-extra/pull/724 points this issue out as well, with two potential fixes [here](https://github.com/kdeldycke/click-extra/pull/724#issuecomment-1674060534) and [here](https://github.com/kdeldycke/click-extra/pull/724#issuecomment-1676428725).

**Comment by kdeldycke** [comment]
This issue has been fixed upstream. Thanks @rasa for the detailed investigation and fix, and thanks @MePsyDuck for the detailed report!

It will be part of the upcoming v4.6.4 release of Click Extra (in a couple of hours).

**Comment by MePsyDuck** [comment]
I understand that this issue has been closed, but I'm still unable to print the correct version of my program. In my case, the command is packaged as a part of python package. The version is defined in `setup.py` and `ExtraVersionOption` both. If I run the script directly as a module, it works. But once it's installed as a package using pip it returns`None` as version. Am I doing something wrong?
